steps:
  - name: gcr.io/cloud-builders/curl:latest
    id: "download fonts"
    waitFor: ["-"]
    dir: src
    entrypoint: sh
    args:
      - -c
      - >-
        echo "{{ define "fontcss" }}" > fontcss.gohtml &&
        curl -L 'https://fonts.googleapis.com/css?family=Inconsolata:400,700|Lora:700&display=swap' >> fontcss.gohtml &&
        echo "{{ end }}" >> fontcss.gohtml

  - name: gcr.io/$PROJECT_ID/imagemagick:latest
    id: "image icons"
    waitFor: ["-"]
    entrypoint: sh
    args:
      - "-c"
      - >-
        mkdir -p dst || true;
        convert imgs/icon.tif -flatten
        '(' +clone -resize 512x512 -quality 60 -write dst/icon-512.png +delete ')'
        '(' +clone -resize 192x192 -quality 60 -write dst/icon-192.png +delete ')'
        '(' +clone -resize 128x128 -quality 60 -write dst/icon-128.png +delete ')'
        '(' +clone -resize 64x64 -quality 60 -write dst/icon-64.png +delete ')'
        '(' +clone -resize 48x48 -quality 60 -write dst/icon-48.png +delete ')'
        '(' +clone -resize 32x32 -quality 60 -write dst/icon-32.png +delete ')'
        '(' +clone -resize 16x16 -quality 60 -write dst/icon-16.png +delete ')'
        -resize 48x48 -quality 60 dst/favicon.ico;
  - name: "gcr.io/$PROJECT_ID/imagemagick:latest"
    id: "image map"
    waitFor: ["-"]
    entrypoint: "sh"
    args:
      - "-c"
      - >-
        mkdir -p dst || true;
        convert -background none -density 1200 -resize 2100x1350 imgs/map.svg -write dst/map.webp dst/map.png;

  - name: "gcr.io/cloud-builders/git"
    id: "push changes"
    entrypoint: "sh"
    env:
      - "GH_KNOWN=github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    args:
      - "-c"
      - >-
        mkdir -p /root/.ssh &&
        cd /root/.ssh &&
        printenv GH_KNOWN > known_hosts && 
        printenv GH_KEY > id_ed25519 &&
        chmod 0600 id_ed25519 && 
        echo Hostname github.com >> config &&
        echo IdentityFile /root/.ssh/id_ed25519 >> config &&
        cd /workspace &&
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && 
        git add * &&
        git commit -m "cloudbuild generate images" &&
        git push git@github.com:seankhliao/com-seankhliao master
    secretEnv:
      - GH_KEY
secrets:
  - kmsKeyName: projects/com-seankhliao/locations/global/keyRings/cloudbuilder/cryptoKeys/github-com-seankhliao
    secretEnv:
      GH_KEY: CiQAM/ObsM2mFZJ5kiPXTNYUjuSGmPClM55nWRR5W8Dhj447rWgSxQMArmoITwLIjloUszOMTHiv5S4D9ik9HnIoO4m7ozSLvBrtG3mQ72f8JGyJRJEPaf879gmMevBFaU5kvd3fb9MwV/zuezm+pX12gcg4p4j5SIO4O4H6hpG8BlRoYvvAgGn0t2vsPqUSYH4TnqtugVPNrsOFzYt6/RA/hwZToCG4BBaTacPM7c4JwAO1cphfiZkDXDqqNrW33lVLnGv/QkUXndVMySXi4u921JUK6TxBm7iDM/acMD3gjl1HI//xa0HZ9S6qfSerfTjkLXpHNFOTGNZBE5Q30TkzsiwKrtU47qOtY7o3ywPtxmC3sjgsdtgQd6mgkbeL6ma/L5H6Yruetk3VJoMXxoOfBvHHqv4k19tQsvDeUwXk7XOkAzbVB0f+oeufNkV3EJpCuOCI/ntiMerYIF36tjN5Y2xF7Bo++AXY9h1hXstU9yV3FUBvwaPOvLDYCBXV2gCJeXtCQwpc16xO4I6KIvk9hT3/Eil6aOtnGDJhC3WFokwXrJ2NI7qg2AEwQOQbCD0bg2O+HavszxZ2I52iWs+kCxGlPzOP8Me7VdU3kbTFX6DaKfG5JC8f7uD/4yNSnGyldGVRlpaYs+AKeZo=
