tags:
  - $COMMIT_SHA
substitutions:
  _IMG: com-seankhliao-sitegen
images:
  - gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$_IMG:latest

steps:
  - id: warm cache
    waitFor: ["-"]
    name: gcr.io/cloud-builders/docker:latest
    args:
      - pull
      - gcr.io/$PROJECT_ID/$_IMG:latest
  - id: build sitegen
    waitFor: ["warm cache"]
    name: gcr.io/cloud-builders/docker:latest
    args:
      - build
      - --cache-from=gcr.io/$PROJECT_ID/$_IMG:latest
      - -t=gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
      - -t=gcr.io/$PROJECT_ID/$_IMG:latest
      - .
