tags:
  - $COMMIT_SHA
  - $SHORT_SHA
  - com-seankhliao
  - com-seankhliao-sitegen
substitutions:
  _IMG: com-seankhliao-sitegen
images:
  - gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$_IMG:$TAG_NAME
  - gcr.io/$PROJECT_ID/$_IMG:latest

steps:
  # - id: build sitegen
  #   name: gcr.io/cloud-builders/docker:latest
  #   args:
  #     - build
  #     - --cache-from=gcr.io/$PROJECT_ID/$_IMG:latest
  #     - -t=gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
  #     - -t=gcr.io/$PROJECT_ID/$_IMG:$TAG_NAME
  #     - -t=gcr.io/$PROJECT_ID/$_IMG:latest
  #     - .
  # - id: sitegen
  #   name: gcr.io/$PROJECT_ID/$_IMG:latest
  - id: generate
    name: seankhliao/webstyle:latest
    args:
      - -in=src
      - -out=dst
  - id: images
    name: seankhliao/ci-imagemagick:latest
    entrypoint: bash
    args:
      - -c
      - |-
        convert \
          "-background" "none" \
          "-density" "1200" \
          "-resize" "1920x1080" \
          "img/map.svg" \
          "-write" "dst/map.png" \
          "-write" "dst/map.webp" \
          "dst/map.jpg"

        convert
          "img/icon.tif" \
          "-flatten" \
          "(" "+clone" "-resize" "512x512" "-quality" "60" "-write" "dst/icon-512.png" "+delete" ")" \
          "(" "+clone" "-resize" "192x192" "-quality" "60" "-write" "dst/icon-192.png" "+delete" ")" \
          "(" "+clone" "-resize" "128x128" "-quality" "60" "-write" "dst/icon-128.png" "+delete" ")" \
          "(" "+clone" "-resize" "64x64" "-quality" "60" "-write" "dst/icon-64.png" "+delete" ")" \
          "(" "+clone" "-resize" "48x48" "-quality" "60" "-write" "dst/icon-48.png" "+delete" ")" \
          "(" "+clone" "-resize" "32x32" "-quality" "60" "-write" "dst/icon-32.png" "+delete" ")" \
          "(" "+clone" "-resize" "16x16" "-quality" "60" "-write" "dst/icon-16.png" "+delete" ")" \
          "-resize" "32x32" "dst/favicon.ico"
  - id: upload
    name: seankhliao/ci-firebase
    args:
      - -P
      - com-seankhiao
      - deploy
