substitutions:
  _IMG: w
  _REG: us.gcr.io/com-seankhliao

steps:
  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - -c=.
      - -f=Dockerfile.base
      - -d=$_REG/$_IMG:base
      - --reproducible
      - --single-snapshot
      - --cache=true
      - --use-new-run
