steps:
  - name: gcr.io/$PROJECT_ID/site-builder:latest
    id: "static site gen"
  - name: gcr.io/$PROJECT_ID/firebase:latest
    id: "deploy"
    entrypoint: sh
    args:
      - -c
      - >-
        [ $BRANCH_NAME = "master" ] && firebase -P $PROJECT_ID deploy
