tags:
  - $COMMIT_SHA
  - $SHORT_SHA
  - com-seankhliao
  - com-seankhliao-sitegen
steps:
  - id: generate
    name: seankhliao/webstyle:latest
    args:
      - -in=src
      - -out=dst
  - id: upload
    name: seankhliao/ci-firebase
    args:
      - -P
      - com-seankhliao
      - deploy
