tags:
  - $COMMIT_SHA
  - $SHORT_SHA
  - com-seankhliao
  - com-seankhliao-sitegen
substitutions:
  _IMG: com-seankhliao-sitegen
images:
  - gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$_IMG:$TAG_NAME
  - gcr.io/$PROJECT_ID/$_IMG:latest

steps:
  - id: build sitegen
    name: gcr.io/cloud-builders/docker:latest
    args:
      - build
      - --cache-from=gcr.io/$PROJECT_ID/$_IMG:latest
      - -t=gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
      - -t=gcr.io/$PROJECT_ID/$_IMG:$TAG_NAME
      - -t=gcr.io/$PROJECT_ID/$_IMG:latest
      - .
  - id: sitegen
    name: gcr.io/$PROJECT_ID/$_IMG:latest
