steps:
  - name: gcr.io/$PROJECT_ID/site-builder:latest
    id: "static site gen"
  - name: gcr.io/$PROJECT_ID/firebase:latest
    id: "deploy"
    args:
      - -P
      - $PROJECT_ID
      - deploy
