substitutions:
  _IMG: com-seankhliao
  _REG: us.gcr.io
tags:
  - $SHORT_SHA
  - $COMMIT_SHA
steps:
  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - -c=.
      - -f=Dockerfile
      - -d=$_REG/$PROJECT_ID/$_IMG:latest
      - -d=$_REG/$PROJECT_ID/$_IMG:$SHORT_SHA
      - --reproducible
      - --single-snapshot
  - id: deploy
    name: gcr.io/cloud-builders/kubectl:latest
    args:
      - set
      - image
      - deployment/$_IMG
      - $_IMG=$_REG/$PROJECT_ID/$_IMG:$SHORT_SHA
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=cluster23
