apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: w16
build:
  artifacts:
  - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/w16
    kaniko:
      reproducible: true
      singleSnapshot: true
      useNewRun: true
      skipUnusedStages: true
      target: w16
      whitelistVarRun: true
      image: gcr.io/kaniko-project/executor:latest
      registryMirror: mirror.gcr.io
  cluster:
    pullSecretName: kaniko-secret
    namespace: skaffold
deploy:
  kubeContext: kind-cluster30
profiles:
  - name: singlepage
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/singlepage
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: singlepage
