apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: w16
build:
  artifacts:
  - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/w16
    kaniko:
      reproducible: true
      singleSnapshot: true
      skipUnusedStages: true
      useNewRun: true
      target: w16
      whitelistVarRun: true
      image: gcr.io/kaniko-project/executor:latest
      registryMirror: mirror.gcr.io
      buildArgs:
        GOPROXY: http://athens.athens.svc.cluster.local
        GOCACHE: /var/run/gobuildcache
        GOMODCACHE: /var/run/gomodcache
      volumeMounts:
        - name: modcache
          mountPath: /var/run/gomodcache
        - name: buildcache
          mountPath: /var/run/gobuildcache
  cluster:
    pullSecretName: kaniko-secret
    pullSecretPath: kaniko-secret
    namespace: skaffold
    volumes:
      - name: modcache
        hostPath:
          path: /opt/kind/cluster30/kaniko-gomodcache
      - name: buildcache
        hostPath:
          path: /opt/kind/cluster30/kaniko-gobuildcache
deploy:
  kubeContext: kind-cluster30
profiles:
  - name: singlepage
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/singlepage
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: singlepage
