// Code generated by generate.go DO NOT EDIT.
package style

import (
	_ "embed"
	"text/template"
)

//go:embed template.gotemplate
var t string

var Template = template.Must(template.New("").Parse(t))
