apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert.yaml
  - deployment.k8s.yaml
  - service.k8s.yaml
images:
  - name: us.gcr.io/com-seankhliao/com-seankhliao
    # newTag: IMAGE_TAG
