steps:
  - id: build
    name: gcr.io/cloud-builders/docker:latest
    dir: $_IMG
    args:
      - build
      - -t=gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
      - -t=gcr.io/$PROJECT_ID/$_IMG:latest
      - .
images:
  - gcr.io/$PROJECT_ID/$_IMG:$SHORT_SHA
  - gcr.io/$PROJECT_ID/$_IMG:latest
substitutions:
  _IMG: site-builder
