name: sitegen
on:
  push:
    brnaches:
      - v7
    paths:
      - ".github/workflows/sitegen.yaml"
      - ".dockerignore"
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "sitegen/*"
      - "vendor/*"
  schedule:
    - cron: "* * */5 * *"
jobs:
  docker:
    name: build container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker login docker.pkg.github.com -u seankhliao -p $PAT
        env:
          PAT: ${{ secrets.GH_PAT }}
      - run: docker build --cache-from docker.pkg.github.com/seankhliao/com-seankhliao/sitegen:latest -t docker.pkg.github.com/seankhliao/com-seankhliao/sitegen:${GITHUB_SHA:0:7} -t docker.pkg.github.com/seankhliao/com-seankhliao/sitegen:latest .
      - run: docker push docker.pkg.github.com/seankhliao/com-seankhliao/sitegen:${GITHUB_SHA:0:7}
      - run: docker push docker.pkg.github.com/seankhliao/com-seankhliao/sitegen:latest
